routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
     return redirect()->route('menu');
});

Route::get('/menu','MenuController@index')->name('menu');
Route::post('/perroF','facturaController@perroF');
Route::post('/refrescoF','facturaController@refrescoF');
Route::post('/facturaGuardar','facturaController@facturaGuardar');
Route::resource('refresco','refrescoController');
Route::resource('perro','perroController');
Route::resource('factura','facturaController');
Route::get('/reportes', 'MenuController@reportes')->name('reportes');
Route::get('/ganancias', 'MenuController@ganancias')->name('ganancias');
Route::get('/tipoPerro', 'MenuController@tipoPerro')->name('tipoPerro');
Route::get('/tipoRefresco', 'MenuController@tipoRefresco')->name('tipoRefresco');
Route::get('/reporteDiario', 'MenuController@reporteDiario')->name('reporteDiario');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/post', 'PostController@form')->name('post.form');
Route::get('/post/save', 'PostController@save')->name('post.save');

resources/views/ganancias.blade.php
@extends('layouts.app')
@section('content')

@if(Auth::user() !== NULL)
@if(Auth::user()->isAdmin())
  @php
    $admin = true
  @endphp
@else
  @php
    $admin = false
  @endphp
@endif
@else
  @php
    $admin = false
  @endphp
@endif
<h1>Menu</h1>
<div class="container">
  <div class="row">
    <div class="col-md">
        <section class="content">
          <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="float-left">
                  <h3>Facturas</h3>
                </div>
                
                  <div class="table-container">
                    <table id="mytable" class="table table-bordered table-striped">
                       <thead>
                         <th>ID</th>
                         <th>Total ventas</th>
                         <th>Total ingresos</th>
                        
                       </thead>
                        <tbody>
                          @if($reporteMensual['factura']->count())  
                          @foreach($reporteMensual['factura'] as $factura)  
                          <tr>
                            <td>{{$factura->_id}}</td>
                            <td>{{$factura->total_ventas}}</td>
                            <td>{{$factura->total_ingresos}}</td>
                        
                           </tr>
                           @endforeach 
                           @else
                           <tr>
                            <td colspan="8">No hay facturas registrados</td>
                          </tr>
                          @endif
                        </tbody>
                    </table>
                  </div>
              </div>
            </div>
          </div>
        </section>
    </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/ingredientes.blade.php
@extends('layouts.app')
@section('content')

@if(Auth::user() !== NULL)
@if(Auth::user()->isAdmin())
  @php
    $admin = true
  @endphp
@else
  @php
    $admin = false
  @endphp
@endif
@else
  @php
    $admin = false
  @endphp
@endif
<h1>Menu</h1>
<div class="container">
  <div class="row">
    <div class="col-md">
        <section class="content">
          <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="float-left">
                  <h3>Facturas</h3>
                </div>
                
                  <div class="table-container">
                    <table id="mytable" class="table table-bordered table-striped">
                       <thead>
                         
                         <th>Numero de ingredientes</th>
                         <th>Total ingredientes</th>
                        
                       </thead>
                        <tbody>
                          @if($ingredientes['factura']->count())  
                          @foreach($ingredientes['factura'] as $factura)  
                          <tr>
                            <td>{{$factura->_id}}</td>
                            <td>{{$factura->total_ingredientes}}</td>
                           
                        
                           </tr>
                           @endforeach 
                           @else
                           <tr>
                            <td colspan="8">No hay facturas registrados</td>
                          </tr>
                          @endif
                        </tbody>
                    </table>
                  </div>
              </div>
            </div>
          </div>
        </section>
    </div>

@endsection

resources/views/menu.blade.php
@extends('layouts.app')
@section('content')

@if(Auth::user() !== NULL)
@if(Auth::user()->isAdmin())
  @php
    $admin = true
  @endphp
@else
  @php
    $admin = false
  @endphp
@endif
@else
  @php
    $admin = false
  @endphp
@endif
<h1>Menu</h1>
<div class="container">
  <div class="row">
    <div class="col-md">
        <section class="content">
          <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="float-left">
                  <h3>Perros</h3>
                </div>
                @if($admin)
                <div class="float-right">
                  <div class="btn-group">
                    <a href="{{ route('perro.create') }}" class="btn btn-info" >Añadir Perro</a>
                  </div>
                </div>
                @endif
                  <div class="table-container">
                    <table id="mytable" class="table table-bordered table-striped">
                       <thead>
                         <th>Nombre</th>
                         <th>Precio</th>
                       </thead>
                        <tbody>
                          @if($data['perros']->count())  
                          @foreach($data['perros'] as $perro)  
                          <tr>
                            <td>{{$perro->nombre}}</td>
                            <td>{{$perro->precio}}</td>
                            @if($admin)
                            <td>
                              <a class="btn btn-primary btn-xs" href="{{ action('perroController@edit', $perro->id)}}" >
                                Editar
                              </a>
                            </td>
                            <td>
                              <form action="{{ action('perroController@destroy',$perro->id)}}" method="post">
                                {{csrf_field()}}
                                <input name="_method" type="hidden" value="DELETE">
                                <button class="btn btn-danger btn-xs" type="submit">
                                  Eliminar
                                </button>
                              </form>
                            </td>
                            @endif
                           </tr>
                           @endforeach 
                           @else
                           <tr>
                            <td colspan="8">No hay perros registrados</td>
                          </tr>
                          @endif
                        </tbody>
                    </table>
                  </div>
              </div>
            </div>
          </div>
        </section>
    </div>


    <div class="col-md">
      <section class="content">
        <div class="col-md-8 col-md-offset-2">
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="float-left"><h3>Refrescos</h3></div>
              @if($admin)
              <div class="float-right">
                <div class="btn-group">
                  <a href="{{ route('refresco.create') }}" class="btn btn-info" >Añadir Refresco</a>
                </div>
              </div>
              @endif
                <div class="table-container">
                  <table id="mytable" class="table table-bordered table-striped">
                     <thead>
                       <th>Nombre</th>
                       <th>Precio</th>
                      <tbody>
                        @if($data['refrescos']->count())  
                        @foreach($data['refrescos'] as $refresco)  
                        <tr>
                          <td>{{$refresco->nombre}}</td>
                          <td>{{$refresco->precio}}</td>
                          @if($admin)
                          <td>
                              <a class="btn btn-primary btn-xs" href="{{ action('refrescoController@edit', $refresco->id)}}" >
                                Editar
                              </a>
                            </td>
                            <td>
                              <form action="{{ action('refrescoController@destroy', $refresco->id) }}" method="post">
                                {{csrf_field()}}
                                <input name="_method" type="hidden" value="DELETE">
                                <button class="btn btn-danger btn-xs" type="submit">
                                  Eliminar
                                </button>
                              </form>
                            </td>
                          @endif
                         </tr>
                         @endforeach 
                         @else
                         <tr>
                          <td colspan="8">No hay refrescos registrados</td>
                        </tr>
                        @endif
                      </tbody>
                  </table>
                </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</div>
@endsection

resources/views/reportediario.blade.php
@extends('layouts.app')
@section('content')

@if(Auth::user() !== NULL)
@if(Auth::user()->isAdmin())
  @php
    $admin = true
  @endphp
@else
  @php
    $admin = false
  @endphp
@endif
@else
  @php
    $admin = false
  @endphp
@endif
<h1>Menu</h1>
<div class="container">
  <div class="row">
    <div class="col-md">
        <section class="content">
          <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="float-left">
                  <h3>Ventas del dia</h3>
                </div>
                
                  <div class="table-container">
                    <table id="mytable" class="table table-bordered table-striped">
                       <thead>
                         <th>Fecha</th>
                         <th>Total ingresos</th>
                        
                       </thead>
                        <tbody>
                          @if($reporteDiario->count())  
                          @foreach($reporteDiario as $factura)  
                          <tr>
                            <td>{{$factura->fecha}}</td>
            z
                            <td>{{$factura->total}}</td>
                        
                           </tr>
                           @endforeach 
                           @else
                           <tr>
                            <td colspan="8">No hay facturas registrados</td>
                          </tr>
                          @endif
                        </tbody>
                    </table>
                  </div>
              </div>
            </div>
          </div>
        </section>
    </div>

@endsection

resources/views/reportes.blade.php
@extends('layouts.app')
@section('content')

@if(Auth::user() !== NULL)
@if(Auth::user()->isAdmin())
  @php
    $admin = true
  @endphp
@else
  @php
    $admin = false
  @endphp
@endif
@else
  @php
    $admin = false
  @endphp
@endif
<h1>Reportes</h1>
<div class="container">
  <div class="row">
    <div class="col-md">
        <section class="content">
          <div class="col-md-10 col-md-offset-2">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="float-left">
                  <a class="navbar-brand" href="{{ url('/ganancias') }}">
                    Ganancias por mes
                </a>
        
                <a class="navbar-brand" href="{{ url('/tipoPerro') }}">
                   Tipos de perro pedidos
                </a>
                <a class="navbar-brand" href="{{ url('/tipoRefresco') }}">
                  Tipos de refresco pedidos
               </a>
                </div>
                
                
        </section>
    </div>
</div>
</div>
@endsection

resources/views/tipoPerro.blade.php
@extends('layouts.app')
@section('content')

@if(Auth::user() !== NULL)
@if(Auth::user()->isAdmin())
  @php
    $admin = true
  @endphp
@else
  @php
    $admin = false
  @endphp
@endif
@else
  @php
    $admin = false
  @endphp
@endif
<h1>Menu</h1>
<div class="container">
  <div class="row">
    <div class="col-md">
        <section class="content">
          <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="float-left">
                  <h3>Facturas</h3>
                </div>
                
                  <div class="table-container">
                    <table id="mytable" class="table table-bordered table-striped">
                       <thead>
                         
                         <th>Tipo Perro</th>
                         <th>Total vendido</th>
                        
                       </thead>
                        <tbody>
                          @if($tipoPerro['factura']->count())  
                          @foreach($tipoPerro['factura'] as $factura)  
                          <tr>
                            <td>{{$factura->_id}}</td>
                            <td>{{$factura->total_ventas}}</td>
                           
                        
                           </tr>
                           @endforeach 
                           @else
                           <tr>
                            <td colspan="8">No hay facturas registrados</td>
                          </tr>
                          @endif
                        </tbody>
                    </table>
                  </div>
              </div>
            </div>
          </div>
        </section>
    </div>

@endsection

resources/views/tipoRefresco.blade.php
@extends('layouts.app')
@section('content')

@if(Auth::user() !== NULL)
@if(Auth::user()->isAdmin())
  @php
    $admin = true
  @endphp
@else
  @php
    $admin = false
  @endphp
@endif
@else
  @php
    $admin = false
  @endphp
@endif
<h1>Menu</h1>
<div class="container">
  <div class="row">
    <div class="col-md">
        <section class="content">
          <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="float-left">
                  <h3>Facturas</h3>
                </div>
                
                  <div class="table-container">
                    <table id="mytable" class="table table-bordered table-striped">
                       <thead>
                         
                         <th>Tipo Perro</th>
                         <th>Total vendido</th>
                        
                       </thead>
                        <tbody>
                          @if($tipoRefresco['factura']->count())  
                          @foreach($tipoRefresco['factura'] as $factura)  
                          <tr>
                            <td>{{$factura->_id}}</td>
                            <td>{{$factura->total_ventas}}</td>
                           
                        
                           </tr>
                           @endforeach 
                           @else
                           <tr>
                            <td colspan="8">No hay facturas registrados</td>
                          </tr>
                          @endif
                        </tbody>
                    </table>
                  </div>
              </div>
            </div>
          </div>
        </section>
    </div>

@endsection