routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
     return redirect()->route('menu');
});

Route::get('/menu','MenuController@index')->name('menu');
Route::post('/perroF','facturaController@perroF');
Route::post('/refrescoF','facturaController@refrescoF');
Route::post('/facturaGuardar','facturaController@facturaGuardar');
Route::resource('refresco','refrescoController');
Route::resource('perro','perroController');
Route::resource('factura','facturaController');
Route::get('/reportes', 'MenuController@reportes')->name('reportes');
Route::get('/ganancias', 'MenuController@ganancias')->name('ganancias');
Route::get('/tipoPerro', 'MenuController@tipoPerro')->name('tipoPerro');
Route::get('/tipoRefresco', 'MenuController@tipoRefresco')->name('tipoRefresco');
Route::get('/reporteDiario', 'MenuController@reporteDiario')->name('reporteDiario');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/post', 'PostController@form')->name('post.form');
Route::get('/post/save', 'PostController@save')->name('post.save');

app/Refresco.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Refresco extends Eloquent
{
	protected $connection = 'mongodb';

    protected $collection = 'refresco_collection';
    protected $fillable = ['nombre','precio'];
}

app/Http/Controllers/refrescoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Refresco;

class refrescoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('refresco.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,['nombre'=> 'required', 'precio' => 'required|numeric']);
        Refresco::create($request->all());
        return redirect()->route('menu')->with('success','¡Refresco añadido de manera exitosa!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $refresco = Refresco::find($id);
        return view('refresco.edit',compact('refresco'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,['nombre'=> 'required', 'precio' => 'required|numeric'],['required'=>'El campo :attribute es obligatorio','numeric' => 'El campo :attribute debe ser un número']);
        Refresco::find($id)->update($request->all());
        return redirect()->route('menu')->with('success','¡Registro de refresco actualizado de manera exitosa!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Refresco::find($id)->delete();
        return redirect()->route('menu')->with('success','¡Registro eliminado de manera exitosa!');
    }
}

resources/views/refresco/create.blade.php
@extends('layouts.app')
@section('content')
	<section class="content">
		<div class="container">
		<div class="row">
		<div class="col-md"></div>
		<div class="col-md-6">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>¡Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif
 
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Agregar refresco</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{ route('refresco.store') }}"  role="form">
							{{ csrf_field() }}
							<div class="row">
								<div class="col-md-2">
									<label>Nombre:</label>
								</div>
								<div class="col-md-10">
									<div class="form-group">
										<input type="text" name="nombre" id="nombre" class="form-control input-sm" placeholder="Nombre">
									</div>
								</div>
							</div>	
							<div class="row">
								<div class="col-md-2">
									<label>Precio:</label>
								</div>
								<div class="col-md-10">
									<div class="form-group">
										<input type="text" name="precio" id="precio" class="form-control input-sm" placeholder="Precio">
									</div>
								</div>

							</div>
							<div class="row">
									<div class="col-md-6">
										<input type="submit"  value="Guardar" class="btn btn-success btn-block">
									</div>
									<div class="col-md-6">
										<a href="{{ route('menu') }}" class="btn btn-info btn-block" >Atrás</a>	
									</div>
							</div>
											
								
						</form>
					</div>
				</div>
 
			</div>
		</div>
		<div class="col-md"></div>
	</div>
	</div>
	</section>

@endsection

resources/views/refresco/edit.blade.php
@extends('layouts.app')
@section('content')
	<section class="content">
		<div class="container">
		<div class="row">
		<div class="col-md"></div>
		<div class="col-md-6">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>¡Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif
 
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Editar Refresco</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{ route('refresco.update',$refresco->id) }}"  role="form">
							{{ csrf_field() }}
							<input name="_method" type="hidden" value="PATCH">
							<div class="row">
								<div class="col-md-2">
									Nombre:
								</div>
								<div class="col-md-10">
									<div class="form-group">
										<input type="text" name="nombre" id="nombre" class="form-control input-sm" value="{{$refresco->nombre}}">
									</div>
								</div>
							</div>	
							<div class="row">
								<div class="col-md-2">
									Precio:
								</div>
								<div class="col-md-10">
									<div class="form-group">
										<input type="text" name="precio" id="precio" class="form-control input-sm" value="{{$refresco->precio}}">
									</div>
								</div>

							</div>
							<div class="row">
									<div class="col-md-6">
										<input type="submit"  value="Actualizar" class="btn btn-success btn-block">
									</div>
									<div class="col-md-6">
										<a href="{{ route('menu') }}" class="btn btn-info btn-block" >Atrás</a>	
									</div>
							</div>
											
								
						</form>
					</div>
				</div>
 
			</div>
		</div>
		<div class="col-md"></div>
	</div>
	</div>
	</section>

@endsection